version: 0.2

phases:
  install:
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - yarn package
artifacts:
  files:
    - "**/*"
  base-directory: dist
